Make IntrospectionRetriever and QueryRetriever public
When using Kotlin, there are problems using Lilo because IntrospectionRetriever and QueryRetriever are not public.

java.lang.IllegalAccessError: failed to access class io.fria.lilo.IntrospectionRetriever from class ...