Make IntrospectionRetriever and QueryRetriever public (#21)
* Make IntrospectionRetriever and QueryRetriever public

When using Kotlin, there are problems using Lilo because IntrospectionRetriever and QueryRetriever are not public.

java.lang.IllegalAccessError: failed to access class io.fria.lilo.IntrospectionRetriever from class ...

* Rollback version

---------

Co-authored-by: Eric Murphy <Eric.Murphy@Cigna.com>